import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, ClipboardList, MapPinned, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ReportCard } from "@/components/report-card";
import { PageIntro, RoadwatchShell } from "@/components/roadwatch-shell";
import { useRoadwatchReports } from "@/lib/roadwatch-data";

export const Route = createFileRoute("/dashboard")({ head: () => ({ meta: [{ title: "Dashboard — RoadWatch" }, { name: "description", content: "See your reporting activity and the live repair queue." }, { property: "og:title", content: "Dashboard — RoadWatch" }, { property: "og:description", content: "See your reporting activity and the live repair queue." }] }), component: DashboardPage });
function DashboardPage() { const reports = useRoadwatchReports(); const mine = reports.filter((report) => report.userId === "demo-user"); return <RoadwatchShell><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><PageIntro eyebrow="Field overview" title="Good morning, Naziya." description="Your neighborhood signal is moving. Pick up where you left off or add a new report." action={<Button asChild className="bg-brand text-paper hover:bg-brand"><Link to="/report">New report <ArrowRight /></Link></Button>} /><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="border-2 border-ink bg-paper p-4 shadow-[4px_4px_0_0_var(--ink)]"><MapPinned className="size-5 text-brand" /><p className="mt-4 font-mono text-3xl font-semibold">{reports.length}</p><p className="font-mono text-[10px] uppercase tracking-[.1em] text-ink/50">Reports on map</p></div><div className="border-2 border-ink bg-paper p-4 shadow-[4px_4px_0_0_var(--ink)]"><ClipboardList className="size-5 text-amber" /><p className="mt-4 font-mono text-3xl font-semibold">{mine.length}</p><p className="font-mono text-[10px] uppercase tracking-[.1em] text-ink/50">Your submissions</p></div><div className="border-2 border-ink bg-paper p-4 shadow-[4px_4px_0_0_var(--ink)]"><ShieldCheck className="size-5 text-mint" /><p className="mt-4 font-mono text-3xl font-semibold">{reports.filter((report) => report.status === "Resolved").length}</p><p className="font-mono text-[10px] uppercase tracking-[.1em] text-ink/50">Roads resolved</p></div></div><div className="mt-8 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><section><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Recent from your account</h2><Link to="/my-reports" className="font-mono text-[10px] uppercase tracking-[.1em] text-brand-deep underline underline-offset-4">View all</Link></div><div className="mt-4 grid gap-3">{mine.map((report) => <ReportCard key={report.id} report={report} compact />)}</div></section><section className="border-2 border-ink bg-brand-deep p-6 text-paper shadow-[5px_5px_0_0_var(--ink)]"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-paper/60">Community pulse</p><h2 className="mt-3 text-3xl font-semibold leading-tight">Every clear pin makes the repair queue smarter.</h2><p className="mt-4 max-w-md text-sm leading-relaxed text-paper/75">See a new hazard? Add it to the live map so neighbors and authorities can act from the same picture.</p><Button asChild className="mt-6 bg-paper text-ink hover:bg-paper/90"><Link to="/map">Explore the map <ArrowRight /></Link></Button></section></div></main></RoadwatchShell>; }
