import { createFileRoute } from "@tanstack/react-router";
import { Filter, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import { RoadwatchMap } from "@/components/roadwatch-map";
import { PageIntro, RoadwatchShell } from "@/components/roadwatch-shell";
import { loadReports, severityClass, type Severity } from "@/lib/roadwatch-data";

export const Route = createFileRoute("/map")({ head: () => ({ meta: [{ title: "Live map — RoadWatch" }, { name: "description", content: "Explore reported potholes and damaged roads on the community map." }, { property: "og:title", content: "Live map — RoadWatch" }, { property: "og:description", content: "Explore reported potholes and damaged roads on the community map." }] }), component: MapPage });
function MapPage() { const [query, setQuery] = useState(""); const [severity, setSeverity] = useState<Severity | "All">("All"); const reports = loadReports(); const filtered = useMemo(() => reports.filter((report) => (severity === "All" || report.severity === severity) && `${report.address} ${report.damageType}`.toLowerCase().includes(query.toLowerCase())), [query, reports, severity]); return <RoadwatchShell><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><PageIntro eyebrow="Community map · live" title="See where the road needs us." description="Browse community reports, then open a marker to see the evidence and current repair status." action={<div className="flex items-center gap-2 rounded-md border-2 border-ink bg-paper px-3 py-2 font-mono text-[11px] uppercase tracking-[.1em]"><Filter className="size-3.5" />{filtered.length} visible</div>} /><div className="mt-7 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div><RoadwatchMap reports={filtered} /></div><div className="space-y-4"><div className="border-2 border-ink bg-paper p-4 shadow-[4px_4px_0_0_var(--ink)]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-ink/45" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search area or damage type" className="h-11 border-ink/20 pl-9" /></div><div className="mt-3 flex flex-wrap gap-2">{(["All", "Low", "Medium", "High", "Critical"] as const).map((option) => <button key={option} type="button" onClick={() => setSeverity(option)} className={`rounded-full border px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.08em] ${severity === option ? "border-brand bg-brand text-paper" : "border-ink/20 bg-cream text-ink/65"}`}>{option}</button>)}</div></div><div className="grid gap-3">{filtered.map((report) => <div key={report.id} className="border-b border-ink/10 pb-3"><div className="flex items-center justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[.1em] text-ink/45">{report.id} · {report.address}</p><h3 className="mt-1 text-sm font-semibold">{report.damageType}</h3></div><span className={`rounded-full px-2 py-1 font-mono text-[10px] uppercase tracking-[.08em] ${severityClass[report.severity]}`}>{report.severity}</span></div></div>)}</div></div></div></main></RoadwatchShell>; }
